### ISSUE TITLE
Seems to require gatsby-plugin-react-helmet without stating so

### ISSUE THREAD

**Issue by joshdavenport** [ashhitch/gatsby-plugin-wpgraphql-seo#26]
Am I correct in that gatsby-plugin-react-helmet is required in order for this plugin to work? Wasn't getting any output in my static output and was going crazy until I added it. Totally makes sense that it's required in order for react-helmet to work and is obvious in hindsight but not having used helmet before, letalone in a Gatsby context so it just didn't occur to me. 

If this is the case I think it should be stated in the docs - happy to PR if I'm right on this

**Comment by miraclemaker** [comment]
Very helpful, thanks. I found that without gatsby-plugin-react-helmet the tags were visible in a normal browser, but they weren't visible in the SSR'd pages and so weren't appearing in the likes of the Facebook debugger.

**Comment by ashhitch** [comment]
Hi yes it is a requirement before the new head API it was installed my default, so prob worth a note now.
Happy to take a PR
