### ISSUE TITLE
Compatible with gatsby 5.0.0?

### ISSUE THREAD

**Issue by mrenzo20** [ashhitch/gatsby-plugin-wpgraphql-seo#30]
Actually seems to be work on my local dev with gatsby 5.3.3, but not in Netlify because in dependences say:
     "peerDependencies": {
        "gatsby": "^3.0.0 || ^4.0.0",
        "react": ">=16",
        "react-helmet": "^6.1.0"
      }
Is possible to add dependence from gatby 5.3.3 to be work on Netlify?

**Comment by ashhitch** [comment]
@mrenzo20 just updated  the peerDependencies to support v5
