### ISSUE TITLE
Meta property og:locale defaults to en_GB

### ISSUE THREAD

**Issue by dwmyke** [ashhitch/gatsby-plugin-wpgraphql-seo#4]
Meta property og:locale defaults to en_GB

I tried adding meta={{property:"og:locale", content:"en_US"}} to Seo component, but that adds a second entry into head. There's now 1 for en_GB and 1 for en_US. 

Is there a better way to override this?

**Comment by ashhitch** [comment]
This is a bug, it should not be hard coded, will get that updated.

It should populate from the inLanguage field.

**Comment by dwmyke** [comment]
Ok got you. Thanks for this plugin, it's great!

**Comment by ashhitch** [comment]
this is now resolved
