### ISSUE TITLE
Gatsby-image changes are not published on npm

### ISSUE THREAD

**Issue by thekishanraval** [ashhitch/gatsby-plugin-wpgraphql-seo#7]
Gatsby image addition is not reflecting when installing via npm.

The package version was updated before the merging the PR for 
[https://github.com/ashhitch/gatsby-plugin-wpgraphql-seo/commit/f0cbc6a5d6df1271d65a75165bdde526031436d5](url)

As the version didn't change, looks like the package hasn't been updated.

<img width="1258" alt="Screenshot 2021-06-11 at 7 11 00 AM" src="https://user-images.githubusercontent.com/9017436/121618572-a05ee700-ca84-11eb-9438-2dbfabc0847c.png">

**Comment by ashhitch** [comment]
Thanks for spotting this
